{
 "title": "Error Event",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "ARO21",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"vip_roulette_sensor_errors\"} |= ``"
    }
   ]
  },
  {
   "title": "ARO11",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"speed_roulette_error_logs\"} |= ``"
    }
   ]
  },
  {
   "title": "SBO11",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"sicbo_error_logs\"} |= ``"
    }
   ]
  }
 ]
}