{
 "title": "SDP Log",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "ARO11 Log", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "ARO11 Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"speed_roulette_error_logs\"} |= ``"
    }
   ]
  },
  { "title": "ARO21 Log", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 } },
  {
   "title": "ARO21 Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"vip_roulette_sensor_errors\"} |= ``"
    }
   ]
  },
  { "title": "SBO11 Log", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 } },
  {
   "title": "SBO11 Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"sicbo_error_logs\"} != \"Failed to connect\""
    }
   ]
  }
 ]
}