version: '3.8'

# Agent Mode - Run on 100.64.0.143 (GC-aro21-agent)
# This compose file runs: Loki Agent (Promtail), Zabbix Agent

services:
  # Loki Agent (Promtail) - Collects logs and sends to remote Loki server
  promtail:
    image: grafana/promtail:latest
    container_name: telemetry-promtail-GC-aro21-agent
    volumes:
      - ./promtail-GC-ARO-002-1-agent.yml:/etc/promtail/config.yml
      # Studio SDP Roulette logs - Main monitoring target
      - /home/rnd/studio-sdp-roulette/self-test-2api.log:/var/log/studio-sdp-roulette/self-test-2api.log:ro
      # SRS and FFmpeg logs - New monitoring targets
      - /home/rnd/share_folder/srs.log:/home/rnd/share_folder/srs.log:ro
      - /home/rnd/share_folder/FFmpeg/ffmpeg_debug.log:/home/rnd/share_folder/FFmpeg/ffmpeg_debug.log:ro
      # Test SRS log file
      - /tmp/test_srs.log:/tmp/test_srs.log:ro
      # Existing logs for backward compatibility
      - ./mock_sicbo.log:/var/log/mock_sicbo.log
      - ./server.log:/var/log/server.log
      - ./tmux-client-3638382.log:/var/log/tmux-client.log
      - ./sdp.log:/var/log/sdp.log
      # Persistent volumes for Promtail data
      - promtail_aro_002_1_positions:/tmp/positions  # Position tracking for log files
      - promtail_aro_002_1_data:/var/lib/promtail    # Promtail internal data
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - monitoring

  # Zabbix Agent - Connects to remote Zabbix server
  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-6.0-latest
    container_name: telemetry-zabbix-agent-GC-aro21-agent
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=GC-ARO-002-1-agent
      - ZBX_SERVER_HOST=100.64.0.113  # Connect to remote Zabbix server
      - ZBX_SERVER_ACTIVE=100.64.0.113
      - ZBX_SERVER_PORT=10051
      - ZBX_ENABLEPERSISTENTBUFFER=1
    volumes:
      - ./zabbix/agent2-GC-ARO-002-1-agent.conf:/etc/zabbix/zabbix_agent2.conf
      - ./zabbix/scripts:/var/lib/zabbix/scripts
      - /sys:/host/sys:ro                       # Mount host sys directory for network interface access
      - /proc/net/dev:/host/proc/net/dev:ro     # Mount host network statistics
      # Persistent volume for Zabbix agent data
      - zabbix_agent_aro_002_1_data:/var/lib/zabbix/agent  # Zabbix agent persistent buffer
    restart: unless-stopped
    networks:
      - monitoring

# Docker volumes for data persistence
volumes:
  promtail_aro_002_1_positions:
    name: telemetry_promtail_aro_002_1_positions
    external: true
  promtail_aro_002_1_data:
    name: telemetry_promtail_aro_002_1_data
    external: true
  zabbix_agent_aro_002_1_data:
    name: telemetry_zabbix_agent_aro_002_1_data
    external: true

networks:
  monitoring:
    driver: bridge
