version: '3.8'

# Agent Mode - Run on 100.64.0.166 (GC-asb11-agent)
# This compose file runs: Loki Agent (Promtail), Zabbix Agent

services:
  # Loki Agent (Promtail) - Collects logs and sends to remote Loki server
  promtail:
    image: grafana/promtail:latest
    container_name: telemetry-promtail-GC-asb11-agent
    volumes:
      - ./promtail-GC-asb11-agent.yml:/etc/promtail/config.yml
      # Studio SDP Roulette logs - Main monitoring target (dynamic date)
      - /home/rnd/studio-sdp-roulette/logs:/var/log/studio-sdp-roulette:ro
      # Existing logs for backward compatibility
      - ./mock_sicbo.log:/var/log/mock_sicbo.log
      - ./server.log:/var/log/server.log  # Additional log file
      - ./tmux-client-3638382.log:/var/log/tmux-client.log  # Additional log file
      - ./sdp.log:/var/log/sdp.log  # SDP error logs
      # Persistent volumes for Promtail data
      - promtail_asb_001_1_positions:/tmp/positions  # Position tracking for log files
      - promtail_asb_001_1_data:/var/lib/promtail    # Promtail internal data
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - monitoring

  # Zabbix Agent - Connects to remote Zabbix server
  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-6.0-latest
    container_name: telemetry-zabbix-agent-GC-asb11-agent
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=GC-asb11-agent
      - ZBX_SERVER_HOST=100.64.0.113  # Connect to remote Zabbix server
      - ZBX_SERVER_ACTIVE=100.64.0.113
      - ZBX_SERVER_PORT=10051
      - ZBX_ENABLEPERSISTENTBUFFER=1
    volumes:
      - ./zabbix/agent2-GC-asb11-agent.conf:/etc/zabbix/zabbix_agent2.conf
      - ./zabbix/scripts:/var/lib/zabbix/scripts
      # Persistent volume for Zabbix agent data
      - zabbix_agent_asb_001_1_data:/var/lib/zabbix/agent  # Zabbix agent persistent buffer
    restart: unless-stopped
    networks:
      - monitoring

# Docker volumes for data persistence
volumes:
  promtail_asb_001_1_positions:
    driver: local
  promtail_asb_001_1_data:
    driver: local
  zabbix_agent_asb_001_1_data:
    driver: local

networks:
  monitoring:
    driver: bridge
