version: '3.8'

# Test Agent Mode - Promtail only for testing
# This compose file runs: Loki Agent (Promtail) for test logs
# Usage: 
#   For GE server: LOKI_SERVER_IP=100.64.0.113 docker compose -f docker-compose-test-agent.yml up -d
#   For TPE server: LOKI_SERVER_IP=100.64.0.160 docker compose -f docker-compose-test-agent.yml up -d

services:
  # Loki Agent (Promtail) - Collects logs and sends to remote Loki server
  promtail-test:
    image: grafana/promtail:latest
    container_name: telemetry-promtail-test-agent
    network_mode: "host"  # Use host network to access remote Loki servers
    volumes:
      - ./promtail-telemetry-promtail-test-agent.yml:/etc/promtail/config.yml
      - /home/ella/kevin/telemetry/test_logs/srs.log:/var/log/srs.log:ro  # Read-only mount of test log
    environment:
      - LOKI_URL=http://${LOKI_SERVER_IP:-100.64.0.113}:3100/loki/api/v1/push
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    restart: unless-stopped

