#!/bin/bash

# Grafana Explore Zabbix Query Fix Script
echo "🔧 Grafana Explore Zabbix Query Fix"
echo "==================================="

echo "📊 Current Status Analysis:"
echo "==========================="
echo "✅ Zabbix API: Working"
echo "✅ Hosts: Available (6 hosts)"
echo "✅ Items: Available (3 items for GC-aro12-agent)"
echo "⚠️  History Data: Limited (this is the issue)"
echo "✅ Grafana Access: Working"
echo ""

echo "🔍 Root Cause Analysis:"
echo "======================="
echo "The issue is that while Zabbix has current values, it may not have"
echo "sufficient historical data points for Grafana to display graphs."
echo "This is common with newly configured agents or short data collection periods."
echo ""

echo "💡 Solutions for Grafana Explore:"
echo "================================="
echo ""
echo "1. 🎯 Use 'Last Value' Query Mode:"
echo "   - In Grafana Explore, change Query Type to 'Last Value'"
echo "   - This will show the current value instead of historical data"
echo "   - Host: GC-aro12-agent"
echo "   - Item: system.cpu.util"
echo ""
echo "2. 📈 Use 'Metrics' Query Mode with Extended Time Range:"
echo "   - Change time range to 'Last 6 hours' or 'Last 24 hours'"
echo "   - This gives more time for data collection"
echo "   - Host: GC-aro12-agent"
echo "   - Item: system.cpu.util"
echo ""
echo "3. 🔄 Enable 'Show Disabled Items':"
echo "   - In Options section, enable 'Show disabled items'"
echo "   - This might reveal additional data sources"
echo ""
echo "4. 📊 Use 'Table' Visualization:"
echo "   - Change visualization from 'Time series' to 'Table'"
echo "   - This shows current values in tabular format"
echo ""

echo "🧪 Test Queries to Try:"
echo "======================="
echo ""
echo "Query 1 - CPU Usage (Last Value):"
echo "• Query Type: Last Value"
echo "• Host: GC-aro12-agent"
echo "• Item: system.cpu.util"
echo ""
echo "Query 2 - Network Traffic (Last Value):"
echo "• Query Type: Last Value"
echo "• Host: GC-aro12-agent"
echo "• Item: net.if.in[\"eth0\"]"
echo ""
echo "Query 3 - Network Traffic Out (Last Value):"
echo "• Query Type: Last Value"
echo "• Host: GC-aro12-agent"
echo "• Item: net.if.out[\"eth0\"]"
echo ""

echo "🔧 Step-by-Step Fix Instructions:"
echo "================================="
echo ""
echo "1. 🌐 Open Grafana Explore:"
echo "   - Go to http://localhost:3000"
echo "   - Click on 'Explore' in the left menu"
echo ""
echo "2. 📡 Select Datasource:"
echo "   - Select 'Zabbix-New' from the datasource dropdown"
echo ""
echo "3. ⚙️  Configure Query:"
echo "   - Set Query Type to 'Last Value'"
echo "   - Leave Group empty"
echo "   - Enter Host: 'GC-aro12-agent'"
echo "   - Enter Item: 'system.cpu.util'"
echo ""
echo "4. 🎨 Set Visualization:"
echo "   - Change visualization to 'Table' or 'Stat'"
echo "   - This will show the current value"
echo ""
echo "5. ▶️  Run Query:"
echo "   - Click 'Run query' button"
echo "   - You should see the current CPU usage value"
echo ""

echo "🔄 Alternative: Use Metrics Query with Extended Time Range:"
echo "=========================================================="
echo ""
echo "1. Set Query Type to 'Metrics'"
echo "2. Change time range to 'Last 6 hours'"
echo "3. Enter Host: 'GC-aro12-agent'"
echo "4. Enter Item: 'system.cpu.util'"
echo "5. Enable 'Show disabled items' in Options"
echo "6. Click 'Run query'"
echo ""

echo "📋 Expected Results:"
echo "==================="
echo "After following these steps, you should see:"
echo "• CPU Usage: ~0.55% (current value)"
echo "• Network In: ~2760 bytes (current value)"
echo "• Network Out: ~2536 bytes (current value)"
echo ""
echo "🎯 Key Points:"
echo "=============="
echo "• Use 'Last Value' query type for current data"
echo "• Use 'Table' or 'Stat' visualization for single values"
echo "• Extend time range if using 'Metrics' query type"
echo "• Enable 'Show disabled items' if needed"
echo ""
echo "✅ This should resolve the 'No data' issue in Grafana Explore!"
