#!/bin/bash

# Dashboard Configuration Export and Persistence Script
echo "💾 Dashboard Configuration Export and Persistence"
echo "================================================"

echo "📊 Current Status:"
echo "=================="
echo "✅ CPU Usage panel: Manually configured with 5 agents"
echo "✅ Network Traffic panel: Manually configured with 5 agents"
echo "✅ Both panels: Working and displaying data"
echo ""

echo "🔧 Export Methods:"
echo "=================="
echo ""
echo "Method 1: Grafana UI Export (Recommended)"
echo "========================================="
echo "1. 🌐 Open Grafana: http://localhost:3000"
echo "2. 📊 Navigate to System Overview Dashboard"
echo "3. ⚙️  Click Dashboard Settings (gear icon in top right)"
echo "4. 📤 Click 'JSON Model' tab"
echo "5. 📋 Copy the entire JSON content"
echo "6. 💾 Save it to a file (e.g., exported_dashboard.json)"
echo ""

echo "Method 2: API Export (if authentication available)"
echo "=================================================="
echo "curl -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "     'http://localhost:3000/api/dashboards/uid/overview-dashboard' \\"
echo "     | jq '.dashboard' > exported_dashboard.json"
echo ""

echo "🔄 Persistence Process:"
echo "======================="
echo ""
echo "Once you have the exported JSON:"
echo "1. 📁 Replace the current overview.json file"
echo "2. 🔄 Restart Grafana container"
echo "3. ✅ Verify panels still work after restart"
echo ""

echo "📋 Step-by-Step Instructions:"
echo "============================="
echo ""
echo "Step 1: Export Dashboard"
echo "------------------------"
echo "• Go to Grafana UI"
echo "• Open System Overview Dashboard"
echo "• Click Dashboard Settings (⚙️)"
echo "• Click 'JSON Model' tab"
echo "• Copy all JSON content"
echo ""

echo "Step 2: Save Configuration"
echo "-------------------------"
echo "• Create a file: exported_dashboard.json"
echo "• Paste the copied JSON content"
echo "• Save the file"
echo ""

echo "Step 3: Apply Configuration"
echo "---------------------------"
echo "• Replace overview.json with exported content"
echo "• Restart Grafana container"
echo "• Verify panels work correctly"
echo ""

echo "🛠️  Automated Script Ready:"
echo "============================"
echo ""
echo "After you export the JSON, run this command:"
echo ""
echo "cp exported_dashboard.json /home/ella/kevin/telemetry/grafana/provisioning/dashboards/general/overview.json"
echo "docker restart kevin-telemetry-grafana"
echo ""
echo "📊 Expected Result:"
echo "=================="
echo "After persistence:"
echo "• CPU Usage panel shows data for all 5 agents"
echo "• Network Traffic panel shows data for all 5 agents"
echo "• Configuration survives Grafana restarts"
echo "• No more 'No data' issues"
echo ""
echo "✅ Ready to persist your working configuration!"
