auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0  # Allow connections from remote agents

ingester:
  lifecycler:
    address: 0.0.0.0  # Allow connections from remote agents
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /tmp/loki/wal
    enabled: false

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false
  creation_grace_period: 10m

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
