auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0  # Allow connections from remote agents

ingester:
  lifecycler:
    address: 0.0.0.0  # Allow connections from remote agents
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /tmp/loki/wal
    enabled: false

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  allow_structured_metadata: false
  creation_grace_period: 10m
  # Limit ingestion rate to handle large log files efficiently
  ingestion_rate_mb: 32  # Reduced from 64MB to 32MB per second
  ingestion_burst_size_mb: 64  # Reduced from 128MB to 64MB burst
  max_streams_per_user: 10000
  max_line_size: 256000
  # Additional storage limits for SRS/FFmpeg logs
  max_chunks_per_query: 2000000
  max_query_series: 5000
  max_query_parallelism: 32
  max_entries_limit_per_query: 10000

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days retention
