server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://100.64.0.113:3100/loki/api/v1/push  # Connect to remote Loki server
    batchwait: 5s
    batchsize: 10
    timeout: 30s

scrape_configs:
  - job_name: mock_sicbo_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mock_sicbo
          instance: GC-aro12-agent  # Agent instance identifier
          __path__: /var/log/mock_sicbo.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (?P<logger>\w+) - (?P<level>\w+) - (?P<message>.*)$'
      - labels:
          level:
          logger:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
          location: "Asia/Taipei"

  - job_name: server_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: server
          instance: GC-aro12-agent
          __path__: /var/log/server.log
    pipeline_stages:
      - timestamp:
          source: time
          format: RFC3339
          location: "Asia/Taipei"

  - job_name: tmux_client_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: tmux_client
          instance: GC-aro12-agent
          __path__: /var/log/tmux-client.log
    pipeline_stages:
      - timestamp:
          source: time
          format: RFC3339
          location: "Asia/Taipei"

  - job_name: sdp_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: sdp
          instance: GC-aro12-agent
          service: sdp_service
          __path__: /var/log/sdp.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (?P<logger>\w+) - (?P<level>\w+) - (?P<game_type>\w+) - (?P<table_name>.*?) - (?P<error_code>\w+) - (?P<error_message>.*)$'
      - labels:
          level:
          logger:
          game_type:
          table_name:
          error_code:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
          location: "Asia/Taipei"

  - job_name: network_stats
    static_configs:
      - targets:
          - localhost
        labels:
          job: network_monitor
          instance: GC-aro11-agent
          interface: enp86s0
          __path__: /var/log/network_stats.log
    pipeline_stages:
      - json:
          expressions:
            rx_bits: rx_bits
      - template:
          source: rx_bits
          template: '{{ .rx_bits }}'
