global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  # Example job for scraping metrics from a Node Exporter
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['localhost:9100']

  # Example job for scraping metrics from a custom application
  # - job_name: 'myapp'
  #   static_configs:
  #     - targets: ['localhost:8080']
