global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "zcam-temperature-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - kevin-telemetry-alertmanager:9093

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  # Example job for scraping metrics from a Node Exporter
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['localhost:9100']

  # Example job for scraping metrics from a custom application
  # - job_name: 'myapp'
  #   static_configs:
  #     - targets: ['localhost:8080']

  # Studio Web Player metrics
  - job_name: 'studio-web-player'
    static_configs:
      - targets: ['192.168.20.9:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Pushgateway metrics
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 15s

  # Telegraf ZCAM HTTP Response metrics
  - job_name: 'telegraf-zcam'
    static_configs:
      - targets: ['kevin-telemetry-telegraf-zcam:9273']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # ZCAM Values Exporter metrics
  - job_name: 'zcam-values'
    static_configs:
      - targets: ['kevin-telemetry-zcam-values-exporter:9274']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
