apiVersion: 1

# Contact points for alert notifications
contactPoints:
  - orgId: 1
    name: webhook-api-trigger
    receivers:
      - uid: webhook-srs-api
        type: webhook
        settings:
          url: http://webhook-service:5000/webhook/grafana
          httpMethod: POST
        disableResolveMessage: false

# Alert rules
groups:
  - orgId: 1
    name: SRS Log Monitoring
    folder: loki
    interval: 30s
    rules:
      - uid: srs-okbps-zero-alert
        title: SRS No Data Alert (okbps=0,0,0)
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 10800
              to: 0
            datasourceUid: fewqf9pkx0p34c
            model:
              expr: 'count_over_time({job="srs_test", instance="telemetry-promtail-test-agent"} |= "okbps=0,0,0" [3h])'
              refId: A
          - refId: B
            relativeTimeRange:
              from: 10800
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 10800
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: B
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          description: 'SRS log shows okbps=0,0,0 which indicates no data transmission. This may indicate a camera or network issue.'
          summary: 'SRS is reporting zero bitrate (okbps=0,0,0) for table {{ $labels.instance }}'
          table_id: 'ARO-001'
        labels:
          severity: critical
          service: srs
          alert_type: no_data
        isPaused: false

# Notification policies
policies:
  - orgId: 1
    receiver: webhook-api-trigger
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 30s
    repeat_interval: 30s
    routes:
      - receiver: webhook-api-trigger
        object_matchers:
          - - service
            - '='
            - srs
        continue: false
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 30s

